### ISSUE TITLE
Setup Handlebars Game page

### ISSUE THREAD

**Issue by JoelKovalcson** [JoelKovalcson/ChattleShip#2]
The root route `/` should send a user to a home or login page.

Page should include the following:
- Header
- Footer with contact information and link to repo
- Either a login form or a login button that will redirect to login form.

**Comment by jaywooski** [comment]
Install tailwindcss to function correctly with handlebars. 
May require PostCSS instead.

**Comment by jaywooski** [comment]
- make page responsive
- Add custom styling (colors, theme, dark mode feature)
